name: Build and test Resurrect package
on:
  push:
    branches: [ 'main' ]
    paths: [ 'src/Resurrect/**', '.github/workflows/build-test-main.yml', 'tests/Resurrect.Tests/**' ]
  pull_request:
    branches: [ 'main' ]
    paths: [ 'src/Resurrect/**', '.github/workflows/build-test-main.yml', 'tests/Resurrect.Tests/**' ]
  
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test
    uses: ./.github/workflows/build-test-reuse.yml
    secrets: inherit
    with:
      PROJECT_FOLDER: 'src/Resurrect'
      TESTS_FOLDER: 'tests/Resurrect.Tests'
